# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssuser',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('prt', 'pro')], default='Free', max_length=32, verbose_name='套餐'),
        ),
    ]
