# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0002_auto_20170730_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssuser',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'pro')], default='Free', max_length=32, verbose_name='套餐'),
        ),
    ]
