# Generated by Django 2.0 on 2018-02-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0002_node_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['node_id'], 'verbose_name_plural': '节点'},
        ),
        migrations.AddField(
            model_name='node',
            name='human_total_traffic',
            field=models.CharField(blank=True, default='1GB', max_length=255, null=True, verbose_name='节点总流量'),
        ),
        migrations.AddField(
            model_name='node',
            name='human_used_traffic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='已用流量'),
        ),
        migrations.AddField(
            model_name='node',
            name='total_traffic',
            field=models.BigIntegerField(default=0, verbose_name='总流量'),
        ),
        migrations.AddField(
            model_name='node',
            name='used_traffic',
            field=models.BigIntegerField(default=0, verbose_name='已用流量'),
        ),
    ]
