# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0003_auto_20170804_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssuser',
            name='method',
            field=models.CharField(choices=[('aes-256-cfb', 'aes-256-cfb'), ('rc4-md5', 'rc4-md5'), ('salsa20', 'salsa20'), ('aes-128-ctr', 'aes-128-ctr')], default='aes-256-cfb', max_length=32, verbose_name='加密类型'),
        ),
        migrations.AddField(
            model_name='ssuser',
            name='obfs',
            field=models.CharField(choices=[('plain', 'plain'), ('http_simple', 'http_simple'), ('http_post', 'http_post'), ('tls1.2_ticket_auth', 'tls1.2_ticket_auth')], default='plain', max_length=32, verbose_name='混淆'),
        ),
        migrations.AddField(
            model_name='ssuser',
            name='protocol',
            field=models.CharField(choices=[('auth_sha1_v4', 'auth_sha1_v4'), ('auth_aes128_md5', 'auth_aes128_md5'), ('auth_aes128_sha1', 'auth_aes128_sha1'), ('auth_chain_a', 'auth_chain_a'), ('origin', 'origin')], default='origin', max_length=32, verbose_name='协议'),
        ),
    ]
