# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0005_trafficlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficlog',
            name='user_id',
            field=models.IntegerField(verbose_name='用户id'),
        ),
    ]
