# Generated by Django 4.2.6 on 2024-01-23 02:45

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0002_alter_dailystats_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailystats",
            name="cost_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                verbose_name="订单总成本",
            ),
        ),
    ]
