
FROM ehco1996/django-sspanel:runtime

LABEL Name=django-sspanel

COPY requirements.txt /tmp/requirements.txt

RUN pip install --no-cache-dir -U -r /tmp/requirements.txt -i https://pypi.douban.com/simple