# Generated by Django 2.0 on 2018-01-05 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssuser',
            name='plan',
        ),
    ]
