# Generated by Django 2.0 on 2018-01-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0002_auto_20171228_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='group',
            field=models.CharField(default='谜之屋', max_length=32, verbose_name='分组名'),
        ),
    ]
