# Generated by Django 2.0 on 2018-01-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0003_auto_20180110_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='NodeInfoLog',
        ),
        migrations.DeleteModel(
            name='NodeOnlineLog',
        ),
    ]
