# Generated by Django 3.1.1 on 2020-11-22 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proxy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxynode",
            name="sequence",
            field=models.IntegerField(
                db_index=True, default=1, help_text="处于序列中的第几位", verbose_name="顺序"
            ),
        ),
    ]
