# Generated by Django 3.1.7 on 2021-03-26 08:57

import apps.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_auto_20201122_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='RayConfig',
            fields=[
                ('proxy_node', models.OneToOneField(help_text='代理节点', limit_choices_to={'node_type': 'ray'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ray_config', serialize=False, to='proxy.proxynode', verbose_name='代理节点')),
                ('ray_tool', models.CharField(choices=[('Xray', 'Xray'), ('v2ray', 'v2ray')], default='v2ray', max_length=32, verbose_name='节点类型')),
                ('config', models.JSONField(default=apps.utils.get_default_ray_config, verbose_name='配置')),
            ],
            options={
                'verbose_name': 'Ray配置',
                'verbose_name_plural': 'Ray配置',
            },
        ),
        migrations.AddField(
            model_name='relaynode',
            name='remark',
            field=models.CharField(default='', max_length=64, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='proxynode',
            name='node_type',
            field=models.CharField(choices=[('ss', 'ss'), ('ray', 'ray')], default='ss', max_length=32, verbose_name='节点类型'),
        ),
        migrations.AlterField(
            model_name='ssconfig',
            name='proxy_node',
            field=models.OneToOneField(help_text='代理节点', limit_choices_to={'node_type': 'ss'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ss_config', serialize=False, to='proxy.proxynode', verbose_name='代理节点'),
        ),
    ]
