# Generated by Django 3.2 on 2021-08-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0006_auto_20210814_2144"),
    ]

    operations = [
        migrations.AddField(
            model_name="relayrule",
            name="rule_name",
            field=models.CharField(
                blank=True, default="", max_length=64, verbose_name="规则名"
            ),
        ),
    ]
