# Generated by Django 3.2 on 2021-10-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0007_relayrule_rule_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxynode",
            name="ehco_web_port",
            field=models.IntegerField(default=0, verbose_name="隧道web端口"),
        ),
        migrations.AddField(
            model_name="proxynode",
            name="ehco_web_token",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="隧道web token"
            ),
        ),
    ]
