# Generated by Django 3.2.12 on 2022-02-02 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0008_auto_20211020_0821"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertrafficlog",
            name="tcp_conn_cnt",
        ),
        migrations.AlterField(
            model_name="proxynode",
            name="node_type",
            field=models.CharField(
                choices=[("ss", "ss"), ("vless", "vless")],
                default="ss",
                max_length=32,
                verbose_name="节点类型",
            ),
        ),
    ]
