# Generated by Django 3.2.15 on 2022-08-27 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proxy", "0009_auto_20220202_1243"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertrafficlog",
            name="proxy_node",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="proxy.proxynode",
                verbose_name="代理节点",
            ),
        ),
        migrations.AlterField(
            model_name="usertrafficlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
    ]
