# Generated by Django 3.2.15 on 2022-08-28 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0010_auto_20220827_1555"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrojanConfig",
            fields=[
                (
                    "proxy_node",
                    models.OneToOneField(
                        help_text="代理节点",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="trojan_config",
                        serialize=False,
                        to="proxy.proxynode",
                        verbose_name="代理节点",
                    ),
                ),
                (
                    "fallback_addr",
                    models.CharField(
                        default="", max_length=32, verbose_name="回落地址"
                    ),
                ),
                (
                    "multi_user_port",
                    models.IntegerField(
                        blank=True,
                        help_text="单端口多用户端口",
                        null=True,
                        verbose_name="多用户端口",
                    ),
                ),
            ],
            options={
                "verbose_name": "SS配置",
                "verbose_name_plural": "SS配置",
            },
        ),
        migrations.AlterField(
            model_name="proxynode",
            name="node_type",
            field=models.CharField(
                choices=[("ss", "ss"), ("trojan", "trojan")],
                default="ss",
                max_length=32,
                verbose_name="节点类型",
            ),
        ),
    ]
