# Generated by Django 3.2.15 on 2022-09-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0012_auto_20220915_2040"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxynode",
            name="provider_remark",
            field=models.CharField(default="", max_length=64, verbose_name="vps备注"),
        ),
    ]
