# Generated by Django 3.2.15 on 2022-10-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0013_proxynode_provider_remark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trojanconfig",
            name="fallback_addr",
            field=models.CharField(default="", max_length=32, verbose_name="回落端口"),
        ),
    ]
