# Generated by Django 4.1.3 on 2023-08-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0016_proxynode_enable_udp"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxynode",
            name="current_used_download_bandwidth_bytes",
            field=models.BigIntegerField(default=0, verbose_name="当前使用的下载带宽"),
        ),
        migrations.AddField(
            model_name="proxynode",
            name="current_used_upload_bandwidth_bytes",
            field=models.BigIntegerField(default=0, verbose_name="当前使用的上传带宽"),
        ),
        migrations.AddField(
            model_name="proxynode",
            name="download_bandwidth_bytes",
            field=models.BigIntegerField(default=0, verbose_name="下载带宽"),
        ),
        migrations.AddField(
            model_name="proxynode",
            name="upload_bandwidth_bytes",
            field=models.BigIntegerField(default=0, verbose_name="上传带宽"),
        ),
        migrations.AlterField(
            model_name="proxynode",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("ss", "ss"),
                    ("trojan", "trojan"),
                    ("ssr", "ssr"),
                    ("vmess", "vmess"),
                    ("vless", "vless"),
                ],
                default="ss",
                max_length=32,
                verbose_name="节点类型",
            ),
        ),
    ]
