# Generated by Django 4.1.3 on 2023-10-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0017_proxynode_current_used_download_bandwidth_bytes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relaynode",
            name="web_token",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                null=True,
                verbose_name="Web验证Token",
            ),
        ),
    ]
