# Generated by Django 4.2.6 on 2023-12-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0018_alter_relaynode_web_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxynode",
            name="ehco_reload_interval",
            field=models.IntegerField(
                default=0, max_length=64, verbose_name="配置重载间隔"
            ),
        ),
    ]
