# Generated by Django 4.2.6 on 2023-12-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0019_proxynode_ehco_reload_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxynode",
            name="ehco_reload_interval",
            field=models.IntegerField(default=0, verbose_name="配置重载间隔"),
        ),
    ]
