# Generated by Django 4.2.6 on 2023-12-20 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("proxy", "0021_alter_usertrafficlog_proxy_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxynode",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="每月成本价格"
            ),
        ),
        migrations.AddField(
            model_name="relaynode",
            name="cost_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="每月成本价格"
            ),
        ),
        migrations.CreateModel(
            name="OccupancyConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occupancy_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="占用 30 天价格"
                    ),
                ),
                (
                    "occupancy_traffic",
                    models.BigIntegerField(default=0, verbose_name="已用流量"),
                ),
                (
                    "occupancy_user_limit",
                    models.PositiveIntegerField(default=0, verbose_name="占用用户限制"),
                ),
                (
                    "proxy_node",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proxy.proxynode",
                        verbose_name="代理节点",
                    ),
                ),
            ],
            options={
                "verbose_name": "占用配置",
                "verbose_name_plural": "占用配置",
            },
        ),
        migrations.CreateModel(
            name="UserProxyNodeOccupancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="开始占用时间"
                    ),
                ),
                ("end_time", models.DateTimeField(verbose_name="结束占用时间")),
                (
                    "traffic_used",
                    models.BigIntegerField(default=0, verbose_name="已用流量"),
                ),
                (
                    "out_of_traffic",
                    models.BooleanField(default=False, verbose_name="流量溢出"),
                ),
                (
                    "occupancy_config_snapshot",
                    models.JSONField(default=dict, verbose_name="快照"),
                ),
                (
                    "proxy_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="proxy.proxynode",
                        verbose_name="代理节点",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "占用记录",
                "verbose_name_plural": "占用记录",
                "index_together": {
                    ("out_of_traffic", "user", "end_time"),
                    ("out_of_traffic", "proxy_node", "end_time"),
                    ("out_of_traffic", "end_time"),
                },
            },
        ),
    ]
