# Generated by Django 4.2.6 on 2024-02-05 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0026_alter_userproxynodeoccupancy_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relayrule",
            name="proxy_node",
        ),
        migrations.RemoveField(
            model_name="relayrule",
            name="rule_name",
        ),
        migrations.AddField(
            model_name="relayrule",
            name="down_traffic",
            field=models.BigIntegerField(default=0, verbose_name="下载流量"),
        ),
        migrations.AddField(
            model_name="relayrule",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=64,
                unique=True,
                verbose_name="规则名",
            ),
        ),
        migrations.AddField(
            model_name="relayrule",
            name="proxy_nodes",
            field=models.ManyToManyField(
                related_name="relay_rules",
                to="proxy.proxynode",
                verbose_name="代理节点",
            ),
        ),
        migrations.AddField(
            model_name="relayrule",
            name="up_traffic",
            field=models.BigIntegerField(default=0, verbose_name="上传流量"),
        ),
    ]
