# Generated by Django 4.2.6 on 2024-02-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0027_remove_relayrule_proxy_node_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relaynode",
            name="relay_sync_duration",
            field=models.IntegerField(null=True, verbose_name="上报间隔(秒)"),
        ),
        migrations.AddField(
            model_name="relaynode",
            name="reload_interval",
            field=models.IntegerField(null=True, verbose_name="配置重载间隔(秒)"),
        ),
        migrations.AddField(
            model_name="relaynode",
            name="web_auth_pass",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Web用户密码"
            ),
        ),
        migrations.AddField(
            model_name="relaynode",
            name="web_auth_user",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Web用户名"
            ),
        ),
        migrations.AddField(
            model_name="relaynode",
            name="web_host",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Web地址"
            ),
        ),
        migrations.AlterField(
            model_name="relaynode",
            name="remark",
            field=models.CharField(
                default="", max_length=64, null=True, verbose_name="备注"
            ),
        ),
    ]
