# Generated by Django 4.2.6 on 2024-03-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("proxy", "0028_relaynode_relay_sync_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proxynode",
            name="native_ip",
            field=models.BooleanField(default=False, verbose_name="是否为原生 ip"),
        ),
    ]
