# Generated by Django 4.1.3 on 2023-09-05 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.openapi.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOpenAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        default=apps.openapi.models._gen_uuid_str,
                        max_length=64,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户秘钥",
                "verbose_name_plural": "用户秘钥",
            },
        ),
    ]
