# Generated by Django 2.0 on 2018-04-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['order'], 'verbose_name_plural': '商品'},
        ),
        migrations.AddField(
            model_name='goods',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='排序'),
        ),
    ]
