# Generated by Django 2.0 on 2018-06-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sspanel', '0002_auto_20180421_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('default', 'default'), ('darkly', 'darkly'), ('flatly', 'flatly'), ('journal', 'journal'), ('materia', 'materia'), ('minty', 'minty'), ('spacelab', 'spacelab'), ('superhero', 'superhero')], default='superhero', max_length=10, verbose_name='主题'),
        ),
    ]
