# Generated by Django 2.0.5 on 2018-06-18 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sspanel', '0003_auto_20180606_0811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitecode',
            old_name='type',
            new_name='code_type',
        ),
        migrations.RemoveField(
            model_name='payrecord',
            name='type',
        ),
        migrations.RemoveField(
            model_name='payrequest',
            name='type',
        ),
        migrations.AddField(
            model_name='payrecord',
            name='charge_type',
            field=models.CharField(default=1, help_text='1：支付宝 2：QQ钱包 3：微信支付', max_length=10, verbose_name='充值类型'),
        ),
        migrations.AddField(
            model_name='payrequest',
            name='charge_type',
            field=models.CharField(default=1, help_text='1：支付宝 2：QQ钱包 3：微信支付', max_length=10, verbose_name='充值类型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level_expire_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='等级有效期'),
        ),
    ]
