# Generated by Django 2.1.7 on 2019-03-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sspanel", "0005_auto_20190224_0625")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sub_type",
            field=models.SmallIntegerField(
                choices=[(0, "只订阅SS"), (1, "只订阅SSR"), (2, "订阅所有")],
                default=2,
                verbose_name="订阅类型",
            ),
        )
    ]
