# Generated by Django 3.1.1 on 2020-11-10 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0005_auto_20201110_2208"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ssnode",
            name="custom_method",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ss_method",
        ),
        migrations.AlterField(
            model_name="ssnode",
            name="method",
            field=models.CharField(
                choices=[
                    ("chacha20-ietf-poly1305", "chacha20-ietf-poly1305"),
                    ("aes-128-gcm", "aes-128-gcm"),
                    ("aes-256-gcm", "aes-256-gcm"),
                ],
                default="aes-256-cfb",
                max_length=32,
                verbose_name="加密类型",
            ),
        ),
    ]
