# Generated by Django 3.1.5 on 2021-01-31 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0008_auto_20210109_2036"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchasehistory",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "用户购买记录",
                "verbose_name_plural": "用户购买记录",
            },
        ),
        migrations.AddField(
            model_name="goods",
            name="user_purchase_count",
            field=models.IntegerField(
                default=0, help_text="0表示不限制", verbose_name="每名用户可购买数量"
            ),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="good_id",
            field=models.IntegerField(db_index=True, default=12, verbose_name="商品ID"),
        ),
        migrations.AddField(
            model_name="purchasehistory",
            name="user_id",
            field=models.IntegerField(db_index=True, default=12, verbose_name="用户ID"),
        ),
    ]
