# Generated by Django 3.1.5 on 2021-03-11 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sspanel", "0009_auto_20210131_0912"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSubLog",
        ),
    ]
