# Generated by Django 3.2 on 2021-06-06 07:24

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0011_auto_20210504_1420"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sub_uid",
            field=models.CharField(
                default=uuid.uuid4, max_length=64, unique=True, verbose_name="sub uuid"
            ),
        ),
    ]
