# Generated by Django 3.2.12 on 2022-02-02 04:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sspanel", "0012_user_uid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="vmess_uuid",
        ),
    ]
