# Generated by Django 2.2.1 on 2019-05-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sspanel", "0013_ssnodeonlinelog")]

    operations = [
        migrations.CreateModel(
            name="SSNode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.IntegerField(unique=True)),
                ("enable", models.BooleanField(db_index=True, default=True)),
                ("level", models.PositiveIntegerField(default=0)),
                (
                    "custom_method",
                    models.BooleanField(default=False, verbose_name="自定义加密"),
                ),
                ("name", models.CharField(max_length=32, verbose_name="名字")),
                ("info", models.CharField(max_length=1024, verbose_name="节点说明")),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("US", "美国"),
                            ("CN", "中国"),
                            ("GB", "英国"),
                            ("SG", "新加坡"),
                            ("TW", "台湾"),
                            ("HK", "香港"),
                            ("JP", "日本"),
                            ("FR", "法国"),
                            ("DE", "德国"),
                            ("KR", "韩国"),
                            ("JE", "泽西岛"),
                            ("NZ", "新西兰"),
                            ("MX", "墨西哥"),
                            ("CA", "加拿大"),
                            ("BR", "巴西"),
                            ("CU", "古巴"),
                            ("CZ", "捷克"),
                            ("EG", "埃及"),
                            ("FI", "芬兰"),
                            ("GR", "希腊"),
                            ("GU", "关岛"),
                            ("IS", "冰岛"),
                            ("MO", "澳门"),
                            ("NL", "荷兰"),
                            ("NO", "挪威"),
                            ("PL", "波兰"),
                            ("IT", "意大利"),
                            ("IE", "爱尔兰"),
                            ("AR", "阿根廷"),
                            ("PT", "葡萄牙"),
                            ("AU", "澳大利亚"),
                            ("RU", "俄罗斯联邦"),
                            ("CF", "中非共和国"),
                        ],
                        default="CN",
                        max_length=5,
                        verbose_name="国家",
                    ),
                ),
                ("server", models.CharField(max_length=128, verbose_name="服务器地址")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("aes-256-cfb", "aes-256-cfb"),
                            ("aes-128-ctr", "aes-128-ctr"),
                            ("rc4-md5", "rc4-md5"),
                            ("salsa20", "salsa20"),
                            ("chacha20", "chacha20"),
                            ("none", "none"),
                        ],
                        default="aes-128-ctr",
                        max_length=32,
                        verbose_name="加密类型",
                    ),
                ),
                (
                    "used_traffic",
                    models.BigIntegerField(default=0, verbose_name="已用流量"),
                ),
                (
                    "total_traffic",
                    models.BigIntegerField(default=1073741824, verbose_name="总流量"),
                ),
            ],
            options={"verbose_name_plural": "SS节点"},
        )
    ]
