# Generated by Django 3.2.15 on 2022-09-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sspanel", "0013_remove_user_vmess_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="更新时间",
                verbose_name="更新时间",
            ),
        ),
    ]
