# Generated by Django 3.2.15 on 2022-10-30 12:29

from django.db import migrations, models

import apps.sspanel.models


class Migration(migrations.Migration):
    dependencies = [
        ("sspanel", "0014_ticket_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSocialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(blank=True, null=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("tg", "tg")],
                        default="tg",
                        max_length=32,
                        verbose_name="平台",
                    ),
                ),
                (
                    "platform_username",
                    models.CharField(max_length=32, verbose_name="用户名"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="创建时间",
                        verbose_name="创建时间",
                    ),
                ),
                ("raw_auth_data", models.JSONField(verbose_name="平台回调信息")),
            ],
            options={
                "verbose_name": "用户社交资料",
                "verbose_name_plural": "用户推荐记录",
                "unique_together": {
                    ("platform", "platform_username", "user_id"),
                    ("platform", "platform_username"),
                },
            },
            bases=(models.Model, apps.sspanel.models.UserMixin),
        ),
    ]
