# Generated by Django 3.2.15 on 2022-10-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sspanel", "0015_usersocialprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersocialprofile",
            name="user_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
