# Generated by Django 2.2.1 on 2019-08-07 03:50
import pendulum

import apps.utils
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("sspanel", "0016_userssconfig_usertraffic")]

    operations = [
        migrations.AlterModelOptions(
            name="usercheckinlog", options={"verbose_name_plural": "用户签到记录"}
        ),
        migrations.AlterModelOptions(
            name="userreflog", options={"verbose_name_plural": "用户推荐记录"}
        ),
        migrations.AlterField(
            model_name="userssconfig",
            name="enable",
            field=models.BooleanField(default=True, verbose_name="是否开启"),
        ),
        migrations.AlterField(
            model_name="userssconfig",
            name="method",
            field=models.CharField(
                choices=[
                    ("aes-256-cfb", "aes-256-cfb"),
                    ("aes-128-ctr", "aes-128-ctr"),
                    ("rc4-md5", "rc4-md5"),
                    ("salsa20", "salsa20"),
                    ("chacha20", "chacha20"),
                    ("none", "none"),
                ],
                default="aes-128-ctr",
                max_length=32,
                verbose_name="加密",
            ),
        ),
        migrations.AlterField(
            model_name="userssconfig",
            name="password",
            field=models.CharField(
                default=apps.utils.get_short_random_string,
                max_length=32,
                verbose_name="密码",
            ),
        ),
        migrations.AlterField(
            model_name="userssconfig",
            name="port",
            field=models.IntegerField(default=1025, unique=True, verbose_name="端口"),
        ),
        migrations.AlterField(
            model_name="userssconfig",
            name="speed_limit",
            field=models.IntegerField(default=0, verbose_name="限速"),
        ),
        migrations.AlterField(
            model_name="usertraffic",
            name="last_use_time",
            field=models.DateTimeField(
                db_index=True,
                default=pendulum.datetime(1996, 2, 2, 0, 0, 0),
                verbose_name="上次使用时间",
            ),
        ),
    ]
