# Generated by Django 4.1.3 on 2022-11-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sspanel", "0017_alter_usersocialprofile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercheckinlog",
            name="date",
            field=models.DateField(db_index=True, verbose_name="记录日期"),
        ),
        migrations.AlterField(
            model_name="userreflog",
            name="date",
            field=models.DateField(db_index=True, verbose_name="记录日期"),
        ),
    ]
