# Generated by Django 2.2.1 on 2019-08-23 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sspanel", "0017_auto_20190807_1150")]

    operations = [
        migrations.CreateModel(
            name="VmessNode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.IntegerField(unique=True)),
                ("level", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=32, verbose_name="名字")),
                ("info", models.CharField(max_length=1024, verbose_name="节点说明")),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("US", "美国"),
                            ("CN", "中国"),
                            ("GB", "英国"),
                            ("SG", "新加坡"),
                            ("TW", "台湾"),
                            ("HK", "香港"),
                            ("JP", "日本"),
                            ("FR", "法国"),
                            ("DE", "德国"),
                            ("KR", "韩国"),
                            ("JE", "泽西岛"),
                            ("NZ", "新西兰"),
                            ("MX", "墨西哥"),
                            ("CA", "加拿大"),
                            ("BR", "巴西"),
                            ("CU", "古巴"),
                            ("CZ", "捷克"),
                            ("EG", "埃及"),
                            ("FI", "芬兰"),
                            ("GR", "希腊"),
                            ("GU", "关岛"),
                            ("IS", "冰岛"),
                            ("MO", "澳门"),
                            ("NL", "荷兰"),
                            ("NO", "挪威"),
                            ("PL", "波兰"),
                            ("IT", "意大利"),
                            ("IE", "爱尔兰"),
                            ("AR", "阿根廷"),
                            ("PT", "葡萄牙"),
                            ("AU", "澳大利亚"),
                            ("RU", "俄罗斯联邦"),
                            ("CF", "中非共和国"),
                        ],
                        default="CN",
                        max_length=5,
                        verbose_name="国家",
                    ),
                ),
                (
                    "used_traffic",
                    models.BigIntegerField(default=0, verbose_name="已用流量"),
                ),
                (
                    "total_traffic",
                    models.BigIntegerField(default=1073741824, verbose_name="总流量"),
                ),
                (
                    "enable",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否开启"
                    ),
                ),
                ("server", models.CharField(max_length=128, verbose_name="服务器地址")),
                (
                    "inbound_tag",
                    models.CharField(default="proxy", max_length=64, verbose_name="标签"),
                ),
                (
                    "port",
                    models.IntegerField(default=10086, unique=True, verbose_name="端口"),
                ),
                ("alert_id", models.IntegerField(default=1, verbose_name="额外ID数量")),
            ],
            options={"verbose_name_plural": "Vmess节点"},
        ),
        migrations.AddField(
            model_name="user",
            name="vmess_uuid",
            field=models.CharField(
                default="", max_length=64, verbose_name="Vmess uuid"
            ),
        ),
    ]
