# Generated by Django 4.1.3 on 2022-11-26 02:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sspanel", "0018_alter_usercheckinlog_date_alter_userreflog_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="ss_password",
            new_name="proxy_password",
        ),
        migrations.RemoveField(
            model_name="user",
            name="ss_port",
        ),
    ]
