# Generated by Django 2.2.1 on 2019-08-26 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sspanel", "0018_auto_20190823_1046")]

    operations = [
        migrations.CreateModel(
            name="NodeOnlineLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.IntegerField()),
                (
                    "node_type",
                    models.CharField(
                        choices=[("ss", "vmess"), ("vmess", "vmess")],
                        default="ss",
                        max_length=32,
                        verbose_name="节点类型",
                    ),
                ),
                ("online_user_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "节点在线记录",
                "ordering": ["-created_at"],
                "index_together": {("node_type", "node_id", "created_at")},
            },
        ),
        migrations.DeleteModel(name="SSNodeOnlineLog"),
    ]
