# Generated by Django 4.2.6 on 2024-01-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sspanel", "0020_ticketmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticketmessage",
            options={
                "ordering": ("ticket", "created_at"),
                "verbose_name": "工单回复",
                "verbose_name_plural": "工单回复",
            },
        ),
        migrations.AlterUniqueTogether(
            name="usersocialprofile",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="usersocialprofile",
            name="platform_user_id",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="用户ID"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usersocialprofile",
            unique_together={
                ("platform", "platform_user_id", "user_id"),
                ("platform", "platform_user_id"),
            },
        ),
    ]
