# Generated by Django 4.2.6 on 2024-01-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sspanel", "0021_alter_ticketmessage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moneycode",
            name="number",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=10,
                max_digits=10,
                null=True,
                verbose_name="金额",
            ),
        ),
        migrations.AlterField(
            model_name="moneycode",
            name="user",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="使用人"
            ),
        ),
    ]
