# Generated by Django 2.2.1 on 2019-10-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sspanel", "0024_auto_20191017_1326")]

    operations = [
        migrations.AlterField(
            model_name="usertraffic",
            name="last_use_time",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="上次使用时间"
            ),
        )
    ]
