# Generated by Django 3.0.2 on 2020-01-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("sspanel", "0027_auto_20200122_1407")]

    operations = [
        migrations.AlterField(
            model_name="emailsendlog",
            name="subject",
            field=models.CharField(db_index=True, max_length=128),
        )
    ]
