# Generated by Django 3.0 on 2020-02-23 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0032_vmessnode_relay_offset_port"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertraffic",
            name="user_id",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AddField(
            model_name="usertraffic",
            name="level",
            field=models.PositiveIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="等级",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sub_type",
            field=models.SmallIntegerField(
                choices=[
                    (0, "只订阅SS"),
                    (1, "只订阅Vmess"),
                    (2, "订阅所有"),
                    (3, "通过Clash订阅所有"),
                ],
                default=2,
                verbose_name="订阅类型",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usertraffic", unique_together={("user_id", "level")},
        ),
    ]
