# Generated by Django 3.0 on 2020-03-01 00:29

import apps.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0032_vmessnode_relay_offset_port"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="download_traffic",
            field=models.BigIntegerField(default=0, verbose_name="下载流量"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_use_time",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="上次使用时间"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ss_method",
            field=models.CharField(
                choices=[
                    ("aes-256-cfb", "aes-256-cfb"),
                    ("aes-128-ctr", "aes-128-ctr"),
                    ("rc4-md5", "rc4-md5"),
                    ("salsa20", "salsa20"),
                    ("chacha20", "chacha20"),
                    ("none", "none"),
                ],
                default="aes-256-cfb",
                max_length=32,
                verbose_name="加密",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ss_password",
            field=models.CharField(
                default=apps.utils.get_short_random_string,
                max_length=32,
                verbose_name="密码",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="ss_port",
            field=models.IntegerField(default=1025, verbose_name="端口"),
        ),
        migrations.AddField(
            model_name="user",
            name="total_traffic",
            field=models.BigIntegerField(default=5368709120, verbose_name="总流量"),
        ),
        migrations.AddField(
            model_name="user",
            name="upload_traffic",
            field=models.BigIntegerField(default=0, verbose_name="上传流量"),
        ),
        migrations.AlterField(
            model_name="user",
            name="sub_type",
            field=models.SmallIntegerField(
                choices=[
                    (0, "只订阅SS"),
                    (1, "只订阅Vmess"),
                    (2, "订阅所有"),
                    (3, "通过Clash订阅所有"),
                ],
                default=2,
                verbose_name="订阅类型",
            ),
        ),
    ]
