# Generated by Django 3.0.3 on 2020-03-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0034_auto_20200302_1537"),
    ]

    operations = [
        migrations.AddField(
            model_name="vmessnode",
            name="ws_host",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="域名"
            ),
        ),
        migrations.AddField(
            model_name="vmessnode",
            name="ws_path",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="websocket_path"
            ),
        ),
    ]
