# Generated by Django 3.0.3 on 2020-03-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0035_auto_20200307_0837"),
    ]

    operations = [
        migrations.RemoveField(model_name="vmessnode", name="offset_port",),
        migrations.RemoveField(model_name="vmessnode", name="relay_host",),
        migrations.RemoveField(model_name="vmessnode", name="relay_offset_port",),
        migrations.RemoveField(model_name="vmessnode", name="relay_port",),
        migrations.AlterField(
            model_name="vmessnode",
            name="ws_path",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="ws_path"
            ),
        ),
        migrations.CreateModel(
            name="RelayRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relay_host", models.CharField(max_length=64, verbose_name="中转地址")),
                ("relay_port", models.CharField(max_length=64, verbose_name="中转端口")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "vmess_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sspanel.VmessNode",
                        verbose_name="Vmess节点",
                    ),
                ),
            ],
            options={"verbose_name_plural": "转发规则",},
        ),
    ]
