# Generated by Django 3.0.3 on 2020-05-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0039_relayrule_isp"),
    ]

    operations = [
        migrations.DeleteModel(name="UserSSConfig",),
        migrations.AddField(
            model_name="ssnode",
            name="port",
            field=models.IntegerField(
                default=19960, help_text="单端口多用户端口", verbose_name="单端口"
            ),
        ),
        migrations.AlterField(
            model_name="ssnode",
            name="method",
            field=models.CharField(
                choices=[
                    ("aes-256-cfb", "aes-256-cfb"),
                    ("aes-128-ctr", "aes-128-ctr"),
                    ("rc4-md5", "rc4-md5"),
                    ("salsa20", "salsa20"),
                    ("chacha20", "chacha20"),
                    ("none", "none"),
                    ("chacha20-ietf-poly1305", "chacha20-ietf-poly1305"),
                ],
                default="aes-256-cfb",
                max_length=32,
                verbose_name="加密类型",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="ss_method",
            field=models.CharField(
                choices=[
                    ("aes-256-cfb", "aes-256-cfb"),
                    ("aes-128-ctr", "aes-128-ctr"),
                    ("rc4-md5", "rc4-md5"),
                    ("salsa20", "salsa20"),
                    ("chacha20", "chacha20"),
                    ("none", "none"),
                    ("chacha20-ietf-poly1305", "chacha20-ietf-poly1305"),
                ],
                default="aes-256-cfb",
                max_length=32,
                verbose_name="加密",
            ),
        ),
    ]
