# Generated by Django 3.0.3 on 2020-05-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0040_auto_20200506_0707"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ssnode",
            name="port",
            field=models.IntegerField(
                blank=True,
                default=19960,
                help_text="单端口多用户端口",
                null=True,
                verbose_name="单端口",
            ),
        ),
    ]
