# Generated by Django 3.0.3 on 2020-05-05 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0041_auto_20200506_0722"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ssnode",
            name="port",
            field=models.IntegerField(
                blank=True, help_text="单端口多用户端口", null=True, verbose_name="单端口"
            ),
        ),
    ]
