# Generated by Django 3.0.3 on 2020-05-12 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sspanel', '0044_auto_20200513_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='good',
        ),
    ]
