# Generated by Django 3.0.3 on 2020-05-17 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0046_auto_20200513_1332"),
    ]

    operations = [
        migrations.CreateModel(
            name="SSRelayRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("relay_host", models.CharField(max_length=64, verbose_name="中转地址")),
                ("relay_port", models.CharField(max_length=64, verbose_name="中转端口")),
                (
                    "remark",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="备注"
                    ),
                ),
                (
                    "isp",
                    models.CharField(
                        choices=[
                            ("中国移动", "中国移动"),
                            ("中国联通", "中国联通"),
                            ("中国电信", "中国电信"),
                            ("BGP三线", "BGP三线"),
                        ],
                        default="BGP三线",
                        max_length=64,
                        verbose_name="ISP线路",
                    ),
                ),
                (
                    "ss_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relay_rules",
                        to="sspanel.SSNode",
                        verbose_name="SS节点",
                    ),
                ),
            ],
            options={"verbose_name_plural": "SS转发规则",},
        ),
        migrations.RenameModel(old_name="RelayRule", new_name="VmessRelayRule",),
        migrations.DeleteModel(name="UserTraffic",),
        migrations.AlterModelOptions(
            name="vmessrelayrule", options={"verbose_name_plural": "Vmess转发规则"},
        ),
        migrations.AlterField(
            model_name="vmessnode",
            name="grpc_host",
            field=models.CharField(
                default="0.0.0.0", max_length=64, verbose_name="grpc地址"
            ),
        ),
        migrations.AlterField(
            model_name="vmessnode",
            name="grpc_port",
            field=models.CharField(
                default="8080", max_length=64, verbose_name="grpc端口"
            ),
        ),
    ]
