# Generated by Django 3.0.3 on 2020-05-17 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0047_auto_20200517_1008"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="sub_type",),
    ]
