# Generated by Django 3.0.6 on 2020-06-19 00:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0048_remove_user_sub_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelayNode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_id", models.IntegerField(unique=True)),
                ("level", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=32, verbose_name="名字")),
                ("info", models.CharField(max_length=1024, verbose_name="节点说明")),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("US", "美国"),
                            ("CN", "中国"),
                            ("GB", "英国"),
                            ("SG", "新加坡"),
                            ("TW", "台湾"),
                            ("HK", "香港"),
                            ("JP", "日本"),
                            ("FR", "法国"),
                            ("DE", "德国"),
                            ("KR", "韩国"),
                            ("JE", "泽西岛"),
                            ("NZ", "新西兰"),
                            ("MX", "墨西哥"),
                            ("CA", "加拿大"),
                            ("BR", "巴西"),
                            ("CU", "古巴"),
                            ("CZ", "捷克"),
                            ("EG", "埃及"),
                            ("FI", "芬兰"),
                            ("GR", "希腊"),
                            ("GU", "关岛"),
                            ("IS", "冰岛"),
                            ("MO", "澳门"),
                            ("NL", "荷兰"),
                            ("NO", "挪威"),
                            ("PL", "波兰"),
                            ("IT", "意大利"),
                            ("IE", "爱尔兰"),
                            ("AR", "阿根廷"),
                            ("PT", "葡萄牙"),
                            ("AU", "澳大利亚"),
                            ("RU", "俄罗斯联邦"),
                            ("CF", "中非共和国"),
                        ],
                        default="CN",
                        max_length=5,
                        verbose_name="国家",
                    ),
                ),
                (
                    "used_traffic",
                    models.BigIntegerField(default=0, verbose_name="已用流量"),
                ),
                (
                    "total_traffic",
                    models.BigIntegerField(default=1073741824, verbose_name="总流量"),
                ),
                (
                    "enable",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="是否开启"
                    ),
                ),
                (
                    "enlarge_scale",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.0"),
                        max_digits=10,
                        verbose_name="倍率",
                    ),
                ),
                ("server", models.CharField(max_length=128, verbose_name="服务器地址")),
            ],
            options={"verbose_name_plural": "中转节点",},
        ),
        migrations.AddField(
            model_name="ssrelayrule",
            name="relay_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sspanel.RelayNode",
                verbose_name="中转节点",
            ),
        ),
        migrations.AddField(
            model_name="vmessrelayrule",
            name="relay_node",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sspanel.RelayNode",
                verbose_name="中转节点",
            ),
        ),
    ]
