# Generated by Django 3.0.7 on 2020-07-04 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0051_auto_20200623_0733"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertrafficlog",
            name="date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
