# Generated by Django 3.0.7 on 2020-07-19 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0053_auto_20200720_0739"),
    ]

    operations = [
        migrations.RemoveField(model_name="ssrelayrule", name="isp",),
        migrations.RemoveField(model_name="vmessrelayrule", name="isp",),
        migrations.AddField(
            model_name="relaynode",
            name="isp",
            field=models.CharField(
                choices=[("移动", "移动"), ("联通", "联通"), ("电信", "电信"), ("BGP", "BGP")],
                default="BGP",
                max_length=64,
                verbose_name="ISP线路",
            ),
        ),
    ]
