# Generated by Django 3.0.7 on 2020-07-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sspanel", "0054_auto_20200720_0758"),
    ]

    operations = [
        migrations.RemoveField(model_name="relaynode", name="total_traffic",),
        migrations.RemoveField(model_name="relaynode", name="used_traffic",),
        migrations.AddField(
            model_name="relaynode",
            name="ehco_listen_type",
            field=models.CharField(
                choices=[("raw", "raw"), ("wss", "wss"), ("mwss", "mwss")],
                default="raw",
                max_length=64,
                verbose_name="隧道监听类型",
            ),
        ),
        migrations.AddField(
            model_name="relaynode",
            name="ehco_ss_lb_port",
            field=models.IntegerField(
                blank=True, help_text="ss负载均衡端口", null=True, verbose_name="ss负载均衡端口"
            ),
        ),
        migrations.AddField(
            model_name="relaynode",
            name="ehco_transport_type",
            field=models.CharField(
                choices=[("raw", "raw"), ("wss", "wss"), ("mwss", "mwss")],
                default="raw",
                max_length=64,
                verbose_name="隧道传输类型",
            ),
        ),
        migrations.AddField(
            model_name="relaynode",
            name="ehco_vmess_lb_port",
            field=models.IntegerField(
                blank=True,
                help_text="vmess负载均衡端口",
                null=True,
                verbose_name="vmess负载均衡端口",
            ),
        ),
        migrations.AddField(
            model_name="relaynode",
            name="level",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
