# Generated by Django 2.0.5 on 2018-06-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='password',
            field=models.CharField(default='password', help_text='单端口多用户时需要', max_length=32, verbose_name='节点密码'),
        ),
    ]
