# Generated by Django 2.0 on 2018-05-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0002_auto_20180421_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssuser',
            name='obfs_param',
            field=models.CharField(
                max_length=128, null=True, blank=True, verbose_name='混淆参数'),
        ),
        migrations.AddField(
            model_name='ssuser',
            name='protocol_param',
            field=models.CharField(
                max_length=128, null=True, blank=True, verbose_name='协议参数'),
        ),
    ]
