# Generated by Django 2.0 on 2018-05-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0003_auto_20180506_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.SmallIntegerField(choices=[(0, '多端口多用户'), (1, '单端口多用户')], default=0, verbose_name='节点类型'),
        ),
        migrations.AddField(
            model_name='node',
            name='obfs_param',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='混淆参数'),
        ),
        migrations.AddField(
            model_name='node',
            name='protocol_param',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='协议参数'),
        ),
    ]
