# Generated by Django 2.0 on 2018-05-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0004_auto_20180507_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='status',
        ),
        migrations.AddField(
            model_name='node',
            name='port',
            field=models.IntegerField(blank=True, help_text='单端口多用户是需要', null=True, verbose_name='节点端口'),
        ),
        migrations.AlterField(
            model_name='node',
            name='custom_method',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='自定义加密'),
        ),
    ]
