# Generated by Django 2.0 on 2018-05-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0005_auto_20180509_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='password',
            field=models.CharField(blank=True, help_text='单端口多用户是需要', max_length=32, null=True, verbose_name='节点密码'),
        ),
    ]
