# Generated by Django 2.0 on 2018-10-03 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0005_auto_20181003_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ssuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='SSUser',
        ),
    ]
