# Generated by Django 2.0.7 on 2018-10-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ssserver", "0007_auto_20181004_1032")]

    operations = [
        migrations.DeleteModel(name="NodeInfoLog"),
        migrations.AddField(
            model_name="node",
            name="ss_type",
            field=models.SmallIntegerField(
                choices=[(0, "SS"), (1, "SSR"), (2, "SS/SSR")],
                default=2,
                verbose_name="SS类型",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="obfs_param",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="混淆参数"
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="port",
            field=models.IntegerField(
                blank=True, default=443, help_text="单端口多用户时需要", verbose_name="节点端口"
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="protocol_param",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="协议参数"
            ),
        ),
    ]
