# Generated by Django 2.2.1 on 2019-05-23 12:19

import apps.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0010_auto_20181219_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suser',
            name='password',
            field=models.CharField(db_column='passwd', default=apps.utils.get_short_random_string, max_length=32, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='ss密码'),
        ),
    ]
