# Generated by Django 2.2.1 on 2019-05-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ssserver", "0011_auto_20190523_2019")]

    operations = [migrations.DeleteModel(name="AliveIp")]
