# Generated by Django 2.2.1 on 2019-05-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0012_delete_aliveip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrafficLog',
        ),
    ]
