# Generated by Django 2.2.1 on 2019-05-28 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssserver', '0013_delete_trafficlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeOnlineLog',
        ),
    ]
