# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rebaterecord',
            options={'ordering': ('-rebatetime',)},
        ),
        migrations.AddField(
            model_name='node',
            name='group',
            field=models.CharField(default='1', max_length=32, verbose_name='分组'),
        ),
    ]
