# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='show',
            field=models.CharField(choices=[('显示', '显示'), ('不显示', '不显示')], default='显示', max_length=32, verbose_name='是否显示'),
        ),
    ]
