# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-24 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aliveip',
            name='node_id',
        ),
        migrations.DeleteModel(
            name='Aliveip',
        ),
    ]
