# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 07:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='level',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9), django.core.validators.MinValueValidator(0)], verbose_name='设置等级'),
        ),
    ]
