# Generated by Django 2.0 on 2018-01-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('info_code', models.CharField(max_length=64, unique=True, verbose_name='流水号')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='金额')),
                ('money_code', models.CharField(max_length=64, unique=True, verbose_name='充值码')),
                ('type', models.CharField(default=1, max_length=10, verbose_name='\n        充值类型\n        1：支付宝 2：QQ钱包 3：微信支付。默认值：1\n        充值类型')),
            ],
            options={
                'verbose_name_plural': '支付宝转账记录',
                'ordering': ('-time',),
            },
        ),
        migrations.CreateModel(
            name='PayRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('info_code', models.CharField(max_length=64, unique=True, verbose_name='流水号')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='金额')),
                ('type', models.CharField(default=1, max_length=10, verbose_name='\n        充值类型\n        1：支付宝 2：QQ钱包 3：微信支付。默认值：1\n        充值类型')),
            ],
            options={
                'verbose_name_plural': '支付宝申请记录',
                'ordering': ('-time',),
            },
        ),
        migrations.DeleteModel(
            name='AlipayRecord',
        ),
        migrations.DeleteModel(
            name='AlipayRequest',
        ),
    ]
