# Generated by Django 2.0 on 2018-01-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0002_auto_20180118_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payrecord',
            options={'ordering': ('-time',), 'verbose_name_plural': '支付转账记录'},
        ),
        migrations.AlterModelOptions(
            name='payrequest',
            options={'ordering': ('-time',), 'verbose_name_plural': '支付申请记录'},
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='default', max_length=10, verbose_name='主题'),
        ),
        migrations.AlterField(
            model_name='payrecord',
            name='type',
            field=models.CharField(default=1, max_length=10, verbose_name='充值类型'),
        ),
        migrations.AlterField(
            model_name='payrequest',
            name='type',
            field=models.CharField(default=1, max_length=10, verbose_name='充值类型'),
        ),
    ]
