# Generated by Django 2.0 on 2018-01-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0003_auto_20180122_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='sale',
            field=models.CharField(choices=[('上架', '上架'), ('下架', '下架')], default='上架', max_length=32, verbose_name='商品状态'),
        ),
    ]
