# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0003_auto_20171006_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='code_id',
            field=models.PositiveIntegerField(default=1, verbose_name='邀请人ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='invitecode_num',
            field=models.PositiveIntegerField(default=1, verbose_name='可生成的邀请码数量'),
        ),
        migrations.AddField(
            model_name='user',
            name='invited_by',
            field=models.PositiveIntegerField(default=1, verbose_name='邀请人id'),
        ),
    ]
