# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0004_auto_20171025_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(default=1, verbose_name='返利人ID')),
                ('money', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='金额')),
                ('rebatetime', models.DateTimeField(auto_now_add=True, verbose_name='返利时间')),
            ],
        ),
        migrations.AddField(
            model_name='invitecode',
            name='isused',
            field=models.BooleanField(default=False, verbose_name='是否使用'),
        ),
    ]
