# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 14:12
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0004_alipayrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInfoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(verbose_name='节点id')),
                ('uptime', models.FloatField(verbose_name='更新时间')),
                ('load', models.CharField(max_length=32, verbose_name='负载')),
                ('log_time', models.IntegerField(verbose_name='日志时间')),
            ],
            options={
                'verbose_name_plural': '节点日志',
                'db_table': 'ss_node_info_log',
            },
        ),
        migrations.CreateModel(
            name='NodeOnlineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(verbose_name='节点id')),
                ('online_user', models.IntegerField(verbose_name='在线人数')),
                ('log_time', models.IntegerField(verbose_name='日志时间')),
            ],
            options={
                'verbose_name_plural': '节点在线记录',
                'db_table': 'ss_node_online_log',
            },
        ),
        migrations.AlterModelOptions(
            name='node',
            options={'ordering': ['id'], 'verbose_name_plural': '节点'},
        ),
        migrations.AddField(
            model_name='node',
            name='custom_method',
            field=models.SmallIntegerField(choices=[(0, 0), (1, 1)], default=0, verbose_name='自定义加密'),
        ),
        migrations.AddField(
            model_name='node',
            name='traffic_rate',
            field=models.FloatField(default=1.0, verbose_name='流量比例'),
        ),
        migrations.AddField(
            model_name='shop',
            name='days',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)], verbose_name='设置等级时间(天)'),
        ),
        migrations.AddField(
            model_name='user',
            name='level_expire_time',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 8, 0), help_text='等级有效期', verbose_name='等级有效期'),
        ),
        migrations.AlterModelTable(
            name='node',
            table='ss_node',
        ),
    ]
