# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0005_auto_20170828_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlipayRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernmae', models.CharField(max_length=64, verbose_name='用户名')),
                ('info_code', models.CharField(max_length=64, unique=True, verbose_name='流水号')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='金额')),
            ],
            options={
                'verbose_name_plural': '支付宝申请记录',
                'ordering': ('-time',),
            },
        ),
    ]
