# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0007_auto_20170829_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodeinfolog',
            options={'ordering': ('-log_time',), 'verbose_name_plural': '节点日志'},
        ),
        migrations.AlterField(
            model_name='node',
            name='status',
            field=models.CharField(choices=[('好用', '好用'), ('维护', '维护'), ('坏了', '坏了')], default='ok', max_length=32, verbose_name='状态'),
        ),
    ]
