# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 00:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0011_auto_20170905_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasehistory',
            options={'ordering': ('-purchtime',), 'verbose_name_plural': '购买记录'},
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='金额'),
        ),
    ]
