# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0013_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='obfs',
            field=models.CharField(choices=[('plain', 'plain'), ('http_simple', 'http_simple'), ('http_simple_compatible', 'http_simple_compatible'), ('http_post', 'http_post'), ('tls1.2_ticket_auth', 'tls1.2_ticket_auth')], default='plain', max_length=32, verbose_name='混淆'),
        ),
    ]
