# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shadowsocks', '0015_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='isopen',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('开启', '开启'), ('关闭', '关闭')], default='关闭', max_length=10, verbose_name='状态'),
        ),
    ]
